const DB_NAME='amify-db', DB_VERSION=1, SONGS_STORE='songs', ALBUMS_STORE='albums', META_STORE='meta';
const audio=document.getElementById('audio');
let songs=[], albums=[], currentId=null, queue=[], queueIndex=0, shuffle=false, repeat=false, currentUrl=null;
let deferredInstall=null;

const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
const fmt=s=>{s=Math.max(0,Math.floor(s||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){document.querySelectorAll('.toast').forEach(x=>x.remove());const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(SONGS_STORE))db.createObjectStore(SONGS_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(ALBUMS_STORE))db.createObjectStore(ALBUMS_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(META_STORE))db.createObjectStore(META_STORE,{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbAll(store){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly');const r=t.objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbPut(store,val){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(val);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function idbDelete(store,id){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function idbClear(store){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).clear();t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function saveMeta(key,value){await idbPut(META_STORE,{key,value})}
async function getMeta(key){const all=await idbAll(META_STORE);return all.find(x=>x.key===key)?.value}

async function load(){songs=await idbAll(SONGS_STORE);albums=await idbAll(ALBUMS_STORE);songs.sort((a,b)=>b.addedAt-a.addedAt);renderAll();}
function getSong(id){return songs.find(s=>s.id===id)}
function getAlbumSongs(albumId){const a=albums.find(x=>x.id===albumId);if(!a)return [];return (a.songIds||[]).map(getSong).filter(Boolean)}

async function fileFromSong(s){
  if(s.handle){try{let p=await s.handle.queryPermission({mode:'read'});if(p!=='granted')p=await s.handle.requestPermission({mode:'read'});if(p==='granted')return await s.handle.getFile()}catch(e){}}
  if(s.blob)return s.blob;
  return null;
}
function sourceLabel(s){return s.handle?'Direct file':'Stored locally'}
function makeSong(file,handle){return {id:uid(),name:file.name.replace(/\.[^/.]+$/,''),fileName:file.name,mime:file.type||'audio/*',size:file.size,duration:0,addedAt:Date.now(),favorite:false,albums:[],handle:handle||null,blob:handle?null:file,source:handle?'handle':'blob',artist:'Unknown artist'}}
async function importHandles(handles){let added=0;for(const handle of handles){try{const file=await handle.getFile();if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|m4a|aac|flac|ogg|opus)$/i.test(file.name))continue;const dup=songs.find(s=>s.fileName===file.name&&s.size===file.size);if(dup){if(!dup.handle){dup.handle=handle;dup.blob=null;dup.source='handle';await idbPut(SONGS_STORE,dup)}continue}const s=makeSong(file,handle);const meta=await readMetadata(file);Object.assign(s,meta);songs.push(s);await idbPut(SONGS_STORE,s);added++}catch(e){console.warn(e)}}songs.sort((a,b)=>b.addedAt-a.addedAt);renderAll();toast(added?`${added} song${added===1?'':'s'} added`:'No new songs found')}
async function importFiles(fileList){let added=0;for(const file of fileList){if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|m4a|aac|flac|ogg|opus)$/i.test(file.name))continue;const dup=songs.find(s=>s.fileName===file.name&&s.size===file.size);if(dup)continue;const s=makeSong(file,null);Object.assign(s,await readMetadata(file));songs.push(s);await idbPut(SONGS_STORE,s);added++}songs.sort((a,b)=>b.addedAt-a.addedAt);renderAll();toast(added?`${added} song${added===1?'':'s'} added`:'No new songs found')}
async function readMetadata(file){return await new Promise(resolve=>{const url=URL.createObjectURL(file),a=new Audio();a.onloadedmetadata=()=>{const duration=a.duration||0;URL.revokeObjectURL(url);resolve({duration})};a.onerror=()=>{URL.revokeObjectURL(url);resolve({duration:0})};a.src=url})}
async function scanDownloads(){if('showDirectoryPicker' in window){try{const dir=await window.showDirectoryPicker({id:'amify-downloads',mode:'read',startIn:'downloads'});const handles=[];for await(const h of dir.values()){if(h.kind==='file')handles.push(h)}await importHandles(handles);await saveMeta('downloadsDirectory',dir);return}catch(e){if(e.name==='AbortError')return;console.warn(e)}}toast('Choose your Downloads folder or select audio files.');$('fileInput').click()}
async function addSongs(){if('showOpenFilePicker' in window){try{const handles=await window.showOpenFilePicker({id:'amify-audio',multiple:true,startIn:'downloads',types:[{description:'Audio files',accept:{'audio/*':['.mp3','.wav','.m4a','.aac','.flac','.ogg','.opus']}}]});await importHandles(handles);return}catch(e){if(e.name==='AbortError')return;console.warn(e)}}$('fileInput').click()}

function renderAll(){renderStats();renderAlbums();renderHomeAlbums();renderSongLists();}
function renderStats(){const today=new Date().toDateString();$('songCount').textContent=songs.length;$('albumCount').textContent=albums.length;$('favoriteCount').textContent=songs.filter(s=>s.favorite).length;$('todayCount').textContent=songs.filter(s=>new Date(s.addedAt).toDateString()===today).length}
function albumCard(a){const count=(a.songIds||[]).map(getSong).filter(Boolean).length;return `<div class="album-card" data-album="${a.id}"><button class="album-menu" data-album-menu="${a.id}" aria-label="Delete album">⋯</button><div class="album-emoji">${esc(a.icon||'🎵')}</div><h3>${esc(a.name)}</h3><small>${count} song${count===1?'':'s'}</small></div>`}
function renderAlbums(){const html=albums.length?albums.map(albumCard).join(''):`<div class="empty" style="grid-column:1/-1"><b>No albums yet</b>Create Hindi, Marathi, Haryanvi, Favorites or any category you want.</div>`;$('albumsGrid').innerHTML=html}
function renderHomeAlbums(){$('homeAlbums').innerHTML=albums.length?albums.slice(0,4).map(albumCard).join(''):`<div class="empty" style="grid-column:1/-1"><b>Start your collection</b>Create your first album, then add songs to it.</div>`}
function songRow(s){const isActive=s.id===currentId;return `<div class="song-row ${isActive?'active':''}" data-song="${s.id}"><button class="song-art play-row" aria-label="Play">${s.favorite?'♥':'♪'}</button><div class="song-text"><div class="song-title">${esc(s.name)}</div><span class="song-sub">${esc(s.artist||'Unknown artist')} · ${esc(sourceLabel(s))}</span></div><span class="song-duration">${fmt(s.duration)}</span><button class="row-btn heart ${s.favorite?'active':''}" data-heart="${s.id}">${s.favorite?'♥':'♡'}</button><button class="row-btn" data-menu="${s.id}">⋮</button></div>`}
function renderSongLists(){const q=($('searchInput').value||'').trim().toLowerCase(),sort=$('sortSelect').value;let list=songs.filter(s=>(s.name+' '+(s.artist||'')).toLowerCase().includes(q));list=[...list].sort((a,b)=>sort==='title'?a.name.localeCompare(b.name):sort==='artist'?(a.artist||'').localeCompare(b.artist||''):sort==='duration'?(a.duration||0)-(b.duration||0):b.addedAt-a.addedAt);$('songsList').innerHTML=list.length?list.map(songRow).join(''):`<div class="empty"><b>${q?'No matching songs':'Your library is empty'}</b>${q?'Try another search.':'Add songs from your Downloads folder to start listening.'}</div>`;$('resultInfo').textContent=`${list.length} song${list.length===1?'':'s'}`;const recent=[...songs].sort((a,b)=>b.addedAt-a.addedAt).slice(0,8);$('homeSongs').innerHTML=recent.length?recent.map(songRow).join(''):`<div class="empty"><b>No recent songs</b>Add a few tracks to see them here.</div>`;$('favoritesList').innerHTML=songs.filter(s=>s.favorite).length?songs.filter(s=>s.favorite).map(songRow).join(''):`<div class="empty"><b>No favorites yet</b>Tap ♡ on any song to save it here.</div>`;$('recentList').innerHTML=recent.length?recent.map(songRow).join(''):`<div class="empty"><b>No recent songs</b>Add songs to build your library.</div>`}

function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(name+'View').classList.add('active-view');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
function bindNavigation(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget)))}

async function createAlbum(){const name=$('albumName').value.trim();if(!name){toast('Enter an album name');return}const a={id:uid(),name,icon:$('albumIcon').value,songIds:[],createdAt:Date.now()};albums.push(a);await idbPut(ALBUMS_STORE,a);closeModal();renderAll();toast(`${name} created`)}
function openAlbum(id){const a=albums.find(x=>x.id===id);if(!a)return;const list=getAlbumSongs(id);document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));const v=$('songsView');v.classList.add('active-view');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));$('songsList').innerHTML=list.length?list.map(songRow).join(''):`<div class="empty"><b>${esc(a.name)} is empty</b>Add songs using the ⋮ menu.</div>`;$('resultInfo').textContent=`${list.length} song${list.length===1?'':'s'} · ${a.icon} ${a.name}`;window.scrollTo({top:0,behavior:'smooth'})}
async function deleteAlbum(id){const a=albums.find(x=>x.id===id);if(!a)return;if(!confirm(`Delete album “${a.name}”? Songs will stay in your library.`))return;await idbDelete(ALBUMS_STORE,id);albums=albums.filter(x=>x.id!==id);renderAll();toast('Album deleted')}
async function toggleFavorite(id){const s=getSong(id);if(!s)return;s.favorite=!s.favorite;await idbPut(SONGS_STORE,s);renderAll()}
async function addToAlbum(songId){if(!albums.length){toast('Create an album first');return}const labels=albums.map((a,i)=>`${i+1}. ${a.name}`).join('\n');const input=prompt(`Add “${getSong(songId).name}” to which album?\n\n${labels}\n\nEnter album number:`);if(!input)return;const idx=Number(input)-1;if(!Number.isInteger(idx)||!albums[idx]){toast('Invalid album');return}const a=albums[idx];if(!a.songIds.includes(songId)){a.songIds.push(songId);await idbPut(ALBUMS_STORE,a);renderAll();toast(`Added to ${a.name}`)}else toast('Already in that album')}
async function removeFromAlbum(songId,albumId){const a=albums.find(x=>x.id===albumId);if(!a)return;a.songIds=a.songIds.filter(x=>x!==songId);await idbPut(ALBUMS_STORE,a);renderAll()}
async function removeSong(id){const s=getSong(id);if(!s)return;if(!confirm(`Remove “${s.name}” from Amify?`))return;songs=songs.filter(x=>x.id!==id);await idbDelete(SONGS_STORE,id);for(const a of albums){if(a.songIds.includes(id)){a.songIds=a.songIds.filter(x=>x!==id);await idbPut(ALBUMS_STORE,a)}}if(currentId===id){audio.pause();currentId=null;playerHide();}renderAll();toast('Removed from Amify')}
async function deleteOriginal(id){const s=getSong(id);if(!s?.handle||!('remove' in FileSystemFileHandle.prototype)){toast('Your browser does not expose file deletion here.');return}if(!confirm(`Delete the original file “${s.fileName}” from your device? This cannot be undone.`))return;try{const p=await s.handle.queryPermission({mode:'readwrite'});const grant=p==='granted'||(await s.handle.requestPermission({mode:'readwrite'}))==='granted';if(!grant)throw new Error('permission');await s.handle.remove();await removeSong(id);toast('Original file deleted');}catch(e){toast('Could not delete the original file')}}

async function playSong(id){const s=getSong(id);if(!s)return;const file=await fileFromSong(s);if(!file){toast('Amify cannot access this file. Re-add the song.');return}if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(file);audio.src=currentUrl;currentId=id;$('playerTitle').textContent=s.name;$('playerArtist').textContent=s.artist||'Unknown artist';$('duration').textContent=fmt(s.duration);$('playerArt').textContent=s.favorite?'♥':'♪';$('player').classList.remove('hidden');try{await audio.play()}catch(e){toast('Tap play to start audio')}$('playBtn').textContent='❚❚';renderAll();}
function playerHide(){$('player').classList.add('hidden');}
function buildQueue(list){queue=list.map(s=>s.id);queueIndex=Math.max(0,queue.indexOf(currentId))}
async function next(){if(!queue.length)buildQueue(songs);if(shuffle)queueIndex=Math.floor(Math.random()*queue.length);else queueIndex=(queueIndex+1)%queue.length;await playSong(queue[queueIndex])}
async function prev(){if(!queue.length)buildQueue(songs);queueIndex=(queueIndex-1+queue.length)%queue.length;await playSong(queue[queueIndex])}

function showSongMenu(id,x,y){const s=getSong(id),m=$('songMenu');m.innerHTML=`<button data-act="play">▶ Play</button><button data-act="fav">${s.favorite?'♡ Remove favorite':'♥ Add to favorites'}</button><button data-act="album">＋ Add to album</button><button data-act="remove">Remove from Amify</button>${s.handle?'<button data-act="delete" class="danger">Delete original file</button>':''}`;m.style.left=Math.min(x,innerWidth-210)+'px';m.style.top=Math.min(y,innerHeight-220)+'px';m.classList.remove('hidden');m.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const act=b.dataset.act;m.classList.add('hidden');if(act==='play')playSong(id);if(act==='fav')toggleFavorite(id);if(act==='album')addToAlbum(id);if(act==='remove')removeSong(id);if(act==='delete')deleteOriginal(id)})}

document.addEventListener('click',e=>{const btn=e.target.closest('[data-menu]');if(btn){e.stopPropagation();showSongMenu(btn.dataset.menu,e.clientX,e.clientY);return}if(!e.target.closest('#songMenu'))$('songMenu').classList.add('hidden');const heart=e.target.closest('[data-heart]');if(heart){e.stopPropagation();toggleFavorite(heart.dataset.heart);return}const play=e.target.closest('.play-row');const row=e.target.closest('[data-song]');if(play&&row){playSong(row.dataset.song);return}const ac=e.target.closest('[data-album]');if(ac&&!e.target.closest('[data-album-menu]'))openAlbum(ac.dataset.album);const am=e.target.closest('[data-album-menu]');if(am){e.stopPropagation();deleteAlbum(am.dataset.album)}});

function openModal(){ $('albumName').value=''; $('modalBackdrop').classList.remove('hidden');$('albumModal').classList.remove('hidden');setTimeout(()=>$('albumName').focus(),50)}
function closeModal(){ $('modalBackdrop').classList.add('hidden');$('albumModal').classList.add('hidden')}

audio.addEventListener('timeupdate',()=>{if(!audio.duration)return;$('progress').value=(audio.currentTime/audio.duration)*100;$('currentTime').textContent=fmt(audio.currentTime)});
audio.addEventListener('loadedmetadata',()=>{$('duration').textContent=fmt(audio.duration);const s=getSong(currentId);if(s){s.duration=audio.duration;idbPut(SONGS_STORE,s)}});
audio.addEventListener('play',()=>$('playBtn').textContent='❚❚');audio.addEventListener('pause',()=>$('playBtn').textContent='▶');audio.addEventListener('ended',()=>{if(repeat){audio.currentTime=0;audio.play();}else next()});$('playBtn').onclick=()=>audio.paused?audio.play():audio.pause();$('nextBtn').onclick=next;$('prevBtn').onclick=prev;$('shuffleBtn').onclick=()=>{shuffle=!shuffle;$('shuffleBtn').style.color=shuffle?'#c084fc':''};$('repeatBtn').onclick=()=>{repeat=!repeat;$('repeatBtn').style.color=repeat?'#c084fc':''};$('progress').oninput=e=>{if(audio.duration)audio.currentTime=(e.target.value/100)*audio.duration};

async function init(){bindNavigation();await load();
  [$('importBtn'),$('mobileImportBtn'),$('heroImportBtn'),$('songsImportBtn')].forEach(b=>b?.addEventListener('click',addSongs));[$('scanBtn'),$('heroScanBtn')].forEach(b=>b?.addEventListener('click',scanDownloads));[$('newAlbumBtn'),$('albumsNewBtn')].forEach(b=>b?.addEventListener('click',openModal));$('createAlbumConfirm').onclick=createAlbum;document.querySelectorAll('.close-modal').forEach(b=>b.onclick=closeModal);$('modalBackdrop').onclick=closeModal;$('fileInput').onchange=e=>importFiles(e.target.files);$('searchInput').oninput=renderSongLists;$('sortSelect').onchange=renderSongLists;
  document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('searchInput')){e.preventDefault();$('searchInput').focus()}if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'&&currentId){e.preventDefault();audio.paused?audio.play():audio.pause()}});
  if('serviceWorker' in navigator){try{await navigator.serviceWorker.register('sw.js')}catch(e){}}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').classList.add('hidden')}};
  $('albumName').addEventListener('keydown',e=>{if(e.key==='Enter')createAlbum()});
}
init();
